module.exports = {
  tokenIssue: 'Improper token',
  tokenMissing: 'Please send token',
  success: 'Success',
  emailSent: "Email sent successfully, We will contact you",
  chapterUpdate: "Chapter name updated successfully",
  chapterDelete: "Chapter deleted successfully",
  invalidPageNo: 'Please select a valid page number',
  deleteSuccess: "User deleted successfully",
  blockSuccess: "User blocked successfully",
  userUpdateSuccess: "User updated successfully",
  userUpdateFail: "Cannot update user email address, because user has already verfied his account",
  userRoleFail: "Cannot update user role Id once it is set",
  userExists: "User with this email and role already exists",
  Fail: "fail",
  invalidComic: "Invalid Comic",
  noRewardPoints: "You do not have any reward points",
  insufficientRewardPoints: "You have less reward points than the required reward points to purchase this comic",
  referralSuccess: "Successfully added 10 referral points to your reward",
  movedPermanently: 'The requested URL has moved to a new URL',
  found: 'The requested URL has moved temporarily to a new URL',
  seeOthers: 'The requested URL can be found under a different URL',
  notModifies:
    'The requested URL has not been modified since the specified date',
  temporaryRedirect: 'The requested URL has moved temporarily to a new URL',
  badRequest: 'Bad Request, request is made with invalid arguments',
  invalidEmail: "Please enter an email in valid format",
  unAuthorized: 'Access token is missing or invalid',
  forbidden: 'Access to the requested URL is forbidden',
  notFound: 'The server can not find the requested URL',
  methodNotAllowed: 'The method specified in the request is not allowed',
  notAcceptable: 'Not Acceptable',
  preconditionFailed: 'Precondition Failed',
  unsupportedMediaType: 'Unsupported Media Type',
  internalServerError:
    'The request was not completed. The server met an unexpected condition',
  notImplemented:
    'The request was not completed. The server did not support the functionality required',
  connectionFailed:
    'The request was not completed. The server is temporarily overloading or down',
  dbError: 'Unable to process your request, please try again',
  sessionExpire: 'Session expires. Please login again',
  invalidDetails: 'Invalid details',
  tryCatch: 'Something went wrong. Please contact admin.',
  registration: 'Registration done successfully',
  emailNotExists: "This email address does not exists",
  invalidRole: "Invalid Role",
  invalidEmail: 'Please insert email address in correct format',
  invalidLoginDetails: 'Invalid login details',
  setPassword: "Please set your password first before login, password link has been sent on your email address",
  duplicateDetails: 'Email Address already exists',
  otpSent: "Your account is not verified, Please verify your account",
  invalidReferralCode: "You have entered an invalid referral code",
  emailVerify: 'Your email is not verified, Please complete email verification process',
  emailVerificationSuccess:
    'Email address successfully verified. Please login to continue',
  emailLinkExpired: 'Link has expired.',
  registrationEmailSubject: 'Welcome to Epool',
  enquirySubject: "Enquiry Email",
  passwordChanged: 'Password changed successfully',
  invalidPassword: 'Password is not valid',
  forgotPasswordSubject: 'ToonSutra, Forgot password link',
  forgotPasswordOTP: "ToonSutra, OTP for reset password",
  resetLink:
    'Reset link sent successfully. You will receive a link shortly if a user is registered.',
  correctOtp: "Your one time password is correct",
  wrongOtp: "Your one time password is wrong",
  resetOTP: "One Time Password has been sent successfully on your email address",
  passwordReset: 'Password has been successfully reset. Please login',
  profileUpdate: 'Profile updated successfully',
  allFieldReq: 'Please fill all required fields',
  noData: 'No information available',
  duplicateUser: 'User details already exist',
  accountDisable:
    'Please contact admin. Your account has been deleted!',
  accountBlocked:
    'Please contact admin. Your account has been blocked!',
  verifyEmail: 'Your email is not verified, Please verify yor email',
  accountActivated: 'Account is activated',
  accountDeactivated: 'Account is deactivated',
  accountReactivated: 'Account is re-activated',
  sendingEmailFailed: 'Having some issue while sending email',
  invalidImage: 'Image type is not valid',
  invalidFile: 'No file selected for upload',
  dateOfBirthUpdate: 'Birth date updated successfully',
  allLanguages: 'Languages fetch successfully',
  fetchSubscriptionPlans: 'All Subscription Plans',
  fetchUserRoles: "All User Roles",
  userGenres: 'User genres set set successfully'
};
